name: wt_console_designer
description: A new Flutter project.
version: 1.0.0+1
homepage: https://github.com/tmcmaster/wt_console_designer
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  shared_preferences:
  flutter_riverpod:
  uuid:
  flutter_colorpicker:
  font_awesome_flutter:
  lottie:
  dart_mappable:
  freezed_annotation:
  json_annotation:

  wt_firepod:
    git:
      url: git@github.com:tmcmaster/wt_firepod.git
  wt_logging:
    git:
      url: git@github.com:tmcmaster/wt_logging.git
  wt_app_scaffold:
    git:
      url: git@github.com:tmcmaster/wt_app_scaffold.git
  date_time_picker:
    git:
      url: git@github.com:tmcmaster/date_time_picker.git
#  device_preview:
#    git:
#      url: git@github.com:tmcmaster/device_preview.git
#      ref: main
#      path: device_preview

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:
  dart_mappable_builder:
  freezed:
  json_serializable:

flutter:
  uses-material-design: true

  assets:
    - assets/
