// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUNitqeW6hl3o5QXNHzt4NOEgTBWRW4eg',
    appId: '1:316517793078:web:2fc0fd1edacac5229a0797',
    messagingSenderId: '316517793078',
    projectId: 'wt-console-designer',
    authDomain: 'wt-console-designer.firebaseapp.com',
    databaseURL: 'https://wt-console-designer-default-rtdb.firebaseio.com',
    storageBucket: 'wt-console-designer.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuIwGVJW463qi0mUt8cVYF3ppPeQINm9A',
    appId: '1:316517793078:android:b80b094e4b0de8609a0797',
    messagingSenderId: '316517793078',
    projectId: 'wt-console-designer',
    databaseURL: 'https://wt-console-designer-default-rtdb.firebaseio.com',
    storageBucket: 'wt-console-designer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8LnbB0H0LF_mD1NnEgNOxeNQsfJpMMNg',
    appId: '1:316517793078:ios:95c3c616afdcbaec9a0797',
    messagingSenderId: '316517793078',
    projectId: 'wt-console-designer',
    databaseURL: 'https://wt-console-designer-default-rtdb.firebaseio.com',
    storageBucket: 'wt-console-designer.appspot.com',
    iosClientId: '316517793078-17e2s3p7rhg0a3qomadidl9vcd55d91s.apps.googleusercontent.com',
    iosBundleId: 'net.wonkytech.wtConsoleDesigner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8LnbB0H0LF_mD1NnEgNOxeNQsfJpMMNg',
    appId: '1:316517793078:ios:95c3c616afdcbaec9a0797',
    messagingSenderId: '316517793078',
    projectId: 'wt-console-designer',
    databaseURL: 'https://wt-console-designer-default-rtdb.firebaseio.com',
    storageBucket: 'wt-console-designer.appspot.com',
    iosClientId: '316517793078-17e2s3p7rhg0a3qomadidl9vcd55d91s.apps.googleusercontent.com',
    iosBundleId: 'net.wonkytech.wtConsoleDesigner',
  );
}
